"""init

Revision ID: 75f5ed60fe36
Revises:
Create Date: 2023-09-25 23:28:25.983636

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75f5ed60fe36"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False, comment="ID"),
        sa.Column(
            "username", sa.String(length=100), nullable=False, comment="ユーザー名"
        ),
        sa.Column(
            "email", sa.String(length=256), nullable=False, comment="メールアドレス"
        ),
        sa.Column(
            "hashed_password",
            sa.String(length=72),
            nullable=False,
            comment="ハッシュ化パスワード",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "todos",
        sa.Column("id", sa.Integer(), nullable=False, comment="ID"),
        sa.Column(
            "title", sa.String(length=300), nullable=False, comment="タイトル"
        ),
        sa.Column(
            "detail", sa.String(length=1000), nullable=False, comment="詳細"
        ),
        sa.Column("due_date", sa.Date(), nullable=False, comment="期限"),
        sa.Column("done", sa.Boolean(), nullable=False, comment="完了フラグ"),
        sa.Column("user_id", sa.Integer(), nullable=False, comment="ユーザーID"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("todos")
    op.drop_table("users")
    # ### end Alembic commands ###
